### ISSUE TITLE
How to connect to KNX/IP router with desktop application?

### ISSUE THREAD

**Issue by AnaKatarina** [lifeemotions/knx.net#10]
Hello everybody :)

First of all, I'm sorry if my english is bad.
I'm Ana Katarina from Croatia and I really, really need solution for my problem. I would be very thankful if you could help me :)

My task is to make a desktop application that will be able to connect with the KNX / IP router and receive telegram from weather station and save that parameters to database. 
I'm using Schneider knx router and ETS 3 software. What should I do? I have no one to ask, KNX is in Croatia still unknown, and I promise that I'm just a student who is stuck with this problem.

I'm using Visual Studio 2013 pro and these classes of Mr. David.
I'm sending you guys how I wrote code for that solution, but it doesn't work.

using KNXLib;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace zavrsni
{
public partial class Form1 : Form
{
string IPadresa;
string Port;

    private static KnxConnection _connection;

    public Form1()
    {
        InitializeComponent();
    }

    private void button1_Click(object sender, EventArgs e)
    {

    }

    private void btnPotvrda_Click(object sender, EventArgs e)
    {
        IPadresa = txtIPadresa.Text;
        Port = txtPort.Text;

        int port = Convert.ToInt32(Port);

        try
        {
            _connection = new KnxConnectionRouting(IPadresa, port);
            _connection.Connect();

            _connection.KnxEventDelegate += new KnxConnection.KnxEvent(Event);
            _connection.KnxStatusDelegate += new KnxConnection.KnxStatus(Event);

            _connection.Action("4/1/1", _connection.ToDataPoint("9.001", 24.0f));
        }
        catch (Exception es)
        {
            txtStatus.Text = es.Message;
        }
    }

    private void Event(string address, string state)
    {
        float temp = (float)_connection.FromDataPoint("9.001", state);
        txtStatus.Text = "Temperature: " + temp;          
    }      
}
}

**Comment by abelsilva** [comment]
If you have an IP router I would advise you to connect using the `KNXConnectionRouting` constructor without any arguments, as you probably have the IP router with the defaults loaded.
Make sure you are connected on the same network as the IP router (check if you can ping it).

You need also to configure the IP router using ETS to forward everything between IP<->TP in order to receive the events from the weather station.

I don't understand why you would send the Action to `4/1/1`, if you only want to receive events you don't need to send this action.

I also don't understand why you would convert every event to a temperature in the `Event` function, make sure you only convert what you want based on the address you configured using ETS.

Finally, I don't know which datapoints you want from the weather station, you will need to see what kind they are, e.g., 9.001 for temperature?
9.001 is implemented
The datapoint for wind isn't.

**Comment by AnaKatarina** [comment]
I can ping it and I configure router to route all telegrams from weather station.
My station sends rain as a bit- rain/no rain, temperature, brightness value-lux, is it morning or evening also as bit and wind speed in meters per second.
Yes, I only want to receive events. How should I fix this line? 
So, in that case I can't use these classes for my project? :/
If I can't, do you know if anybody have similar library with all that datapoint?

**Comment by AnaKatarina** [comment]
![image](https://cloud.githubusercontent.com/assets/12157530/7789089/823fef8e-0254-11e5-963f-80070beb5d28.png)

**Comment by abelsilva** [comment]
With this library you could receive:
* bit- rain/no rain
* temperature (if it is 9.001)
* morning/evening (if it is bit and not a special datapoint)

wind speed and brightness you need to check the weather station specs, but they are probably special datapoints and not generic byte values

You have the option to receive the values as byte and convert them, but you need to see the datapoint specs in order to know how to convert.

Regarding your code, you only need to remove the `Action` call and the `FromDataPoint` call.
This will allow you to start seeing something.

I've seen other libraries but I've never used any of them.

**Comment by abelsilva** [comment]
`9.005` is not implemented in this library at the moment

**Comment by AnaKatarina** [comment]
Can you maybe link me or recommend some libraries which can work with all datapoints I need? Maybe here on github?

**Comment by abelsilva** [comment]
The only one I recall is Calimero but is in Java, this one should have everything you need (i.e., all datapoints available)
http://calimero-project.github.io/

In .net I've stumbled upon some but I don't recall the names, a simple search should show them

**Comment by AnaKatarina** [comment]
Well, then I'll try with Java. Thank you very much for your help :)

**Comment by abelsilva** [comment]
no problem! good luck!

**Comment by AnaKatarina** [comment]
In my university, LAN network is unicast, so it's really confusing to me because in every library I' ve been seen multicast address. On this picture below is shown multicast for routing, and unicast for tunneling. So my question is can I on the second IP address (picture below) write for example 192.168.2.125, and configure IP address on my laptop as 192.168.2.126 and then use that second unicast address for routing? Will that work? 
So at the application I will write that second address and default port 3671 and application will be connected to KNX/IP router? Is it enough to use only classes for connect to router and routing to receive telegrams?

If you have time I would love to if you can explain to me this procedure because you are an expert and it would be great hear your expert opinion, please 

![image](https://cloud.githubusercontent.com/assets/12157530/7801176/b917717c-0320-11e5-8fc6-a13552fc1d1e.png)

**Comment by AnaKatarina** [comment]
At my university*

**Comment by abelsilva** [comment]
That is only for the multicast address, check if the `IP-Configuration 2` is to set the IP address

![image](https://cloud.githubusercontent.com/assets/1167088/7801212/154dbe9a-0319-11e5-9c24-d65d9fa0f3aa.png)

**Comment by AnaKatarina** [comment]
I see, but what is below Mulitcast address? Ip address for what? Unicast? At IP-Configuration 2 is subnet mask and gateway

What really bothers me is can I do an application for receiving telegrams if I use unicast? 

![image](https://cloud.githubusercontent.com/assets/12157530/7801340/6e5c9fba-0323-11e5-891e-91f0e173cda9.png)

**Comment by abelsilva** [comment]
Please send a screenshot of the configuration of the IP router from ETS, instead of a screenshot from a PDF

Different devices have different configuration menus

**Comment by AnaKatarina** [comment]
![image](https://cloud.githubusercontent.com/assets/12157530/7801570/430ccb10-0327-11e5-848c-b6a11ab53a60.png)

![image](https://cloud.githubusercontent.com/assets/12157530/7801571/4b78e6d0-0327-11e5-8f00-43f7bb0a293a.png)

![image](https://cloud.githubusercontent.com/assets/12157530/7801580/7da5413a-0327-11e5-8686-06d5b9f26522.png)

**Comment by abelsilva** [comment]
I missed this in the first screenshot

Change the IP address here and connect using Tunneling (unicast mode)

![image](https://cloud.githubusercontent.com/assets/1167088/7801960/2d270c9a-0325-11e5-86dd-01f98e5dd7da.png)

**Comment by abelsilva** [comment]
Sorry

Wrong image
![image](https://cloud.githubusercontent.com/assets/1167088/7801974/72c4b0e0-0325-11e5-954f-a08d5edce30f.png)
